[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/"
  to = "https://arrow-flicks-yumentsel.vercel.app/"
  status = 200
  force = true